import os
import re
import subprocess
from dataclasses import dataclass, field

from .citation_validation import parse_quotes


@dataclass
class ReportSection:
    title: str
    content: str
    subsections: list["ReportSection"] = field(default_factory=list)


@dataclass
class ReportData:
    title: str
    query: str
    sections: list[ReportSection]
    references: list = field(default_factory=list)
    figures: list[str] = field(default_factory=list)


class LaTeXReport:
    def generate(self, data: ReportData, output_dir: str, logger=None) -> str:
        tex_path = os.path.join(output_dir, "report.tex")
        bib_path = os.path.join(output_dir, "references.bib")
        has_bib = os.path.exists(bib_path) and os.path.getsize(bib_path) > 0
        body = self._build_body(data)
        tex = self._wrap_document(data.title, body, has_bib, output_dir)

        with open(tex_path, "w") as f:
            f.write(tex)

        self._compile(tex_path, logger)

        pdf_path = tex_path.replace(".tex", ".pdf")
        if os.path.exists(pdf_path):
            os.remove(tex_path)
            self._cleanup_aux_files(output_dir)

        return pdf_path

    def _cleanup_aux_files(self, output_dir: str) -> None:
        for ext in [".log", ".aux", ".blg", ".bbl", ".out"]:
            path = os.path.join(output_dir, f"report{ext}")
            if os.path.exists(path):
                os.remove(path)

    def _build_body(self, data: ReportData) -> str:
        lines = [f"\\section{{Query}}\n{self._escape(data.query)}\n"]
        for sec in data.sections:
            lines.append(sec.content)
        return "\n".join(lines)

    def _wrap_document(self, title: str, body: str, has_bib: bool, output_dir: str) -> str:
        bib_section = ""
        if has_bib:
            bib_section = self._build_references_section(output_dir)
        return f"""\\documentclass{{article}}
\\usepackage{{graphicx}}
\\usepackage{{xcolor}}
\\usepackage{{amssymb}}
\\usepackage{{booktabs}}
\\usepackage[margin=1in]{{geometry}}
\\newcommand{{\\fitbox}}[1]{{\\resizebox{{\\textwidth}}{{!}}{{#1}}}}
\\title{{{self._escape(title)}}}
\\author{{HEP Multi-agent System \\\\ Argonne Computational Sciences Division}}
\\begin{{document}}
\\maketitle
\\noindent\\textit{{\\small This report was autonomously generated by an LLM-based multi-agent system. All content, analysis, and conclusions should be independently verified.}}
\\vspace{{1em}}

{body}
{bib_section}
\\end{{document}}
"""

    def _build_references_section(self, output_dir: str) -> str:
        bib_path = os.path.join(output_dir, "references.bib")
        refs = self._parse_bib(bib_path)

        lines = [
            "\\section{References}",
            "\\textit{\\small LLM-generated references. Quotes validated against source text.}",
            "\\vspace{1em}",
        ]

        for ref in refs:
            arxiv_id = ref.get("eprint", "")
            check = "\\textcolor{green}{$\\checkmark$}"
            lines.append(f"\n{check} \\textbf{{{self._escape(ref.get('title', ''))}}} ({ref.get('year', '')})")
            lines.append(f"\\\\{self._escape(ref.get('author', ''))} -- arXiv:{arxiv_id}")
            for q in parse_quotes(ref.get("note", "")):
                lines.append(f"\\\\\\quad\\textit{{``{self._escape(q)}''}}")
            lines.append("\\vspace{0.5em}")

        return "\n".join(lines)

    def _parse_bib(self, bib_path: str) -> list:
        if not os.path.exists(bib_path):
            return []
        with open(bib_path) as f:
            content = f.read()
        refs = []
        for match in re.finditer(r"@\w+\{[^,]+,(.+?)\n\}", content, re.DOTALL):
            ref = {}
            for field in ["title", "author", "year", "eprint", "note"]:
                m = re.search(rf"{field}\s*=\s*\{{(.+?)\}}", match.group(1), re.DOTALL)
                if m:
                    ref[field] = m.group(1).strip()
            refs.append(ref)
        return refs

    def _escape(self, text: str) -> str:
        for char in ["&", "%", "$", "#", "_", "{", "}"]:
            text = text.replace(char, f"\\{char}")
        return text

    def _compile(self, tex_path: str, logger=None) -> bool:
        d = os.path.dirname(tex_path)
        try:
            subprocess.run(
                ["pdflatex", "-interaction=nonstopmode", "-output-directory", d, tex_path],
                capture_output=True,
                timeout=60,
            )
            pdf_path = tex_path.replace(".tex", ".pdf")
            if not os.path.exists(pdf_path):
                log_path = tex_path.replace(".tex", ".log")
                if os.path.exists(log_path):
                    with open(log_path) as f:
                        for line in f:
                            if line.startswith("! LaTeX Error:"):
                                if logger:
                                    logger.log("LaTeX", line.strip()[2:])
                                break
                return False
            return True
        except subprocess.TimeoutExpired:
            if logger:
                logger.log("LaTeX Error", "Compilation timed out")
            return False
        except FileNotFoundError:
            if logger:
                logger.log("LaTeX Error", "pdflatex not found - install LaTeX")
            return False
